In [33]:
# Getting Started with Pandas
# Objective: Introduce students to using Pandas for data analysis by loading data into Pandas
# DataFrames.

# Question 1: Importing Pandas and Loading a CSV File
# 1. Open your Jupyter Notebook or a Python environment.
# 2. Import the pandas library.
# 3. Load a CSV file into a DataFrame.
import pandas as pd 
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Salary': [50000, 60000, 70000]
}
df=pd.DataFrame(data)
df.head()
df.info()




# Question 2: Displaying the First Few Rows
# 4. Use the head() method to display the first five rows of the DataFrame.
   




# Question 3: Basic Data Information
# 5. Use the info() method to get a concise summary of the DataFrame.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes

In [34]:
# Data Inspection & Selection
# Objective: Learn how to inspect data and select specific data points.

# Question 1: Inspecting Column Data Types
# 6. Use the dtypes attribute to inspect the data types of each column.
import pandas as pd 
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'Salary': [50000, 60000, 70000]
}
df=pd.DataFrame(data)
print(df.dtypes)
ac = df['Age']
print(ac)
sr = df[1:3]
print(sr)





# Question 2: Selecting Columns
# 7. Select a single column from the DataFrame.
   




# Question 3: Slicing Rows
# 8. Select specific rows using slicing.

Name      object
Age        int64
Salary     int64
dtype: object
0    25
1    30
2    35
Name: Age, dtype: int64
      Name  Age  Salary
1      Bob   30   60000
2  Charlie   35   70000

In [35]:
# Data Cleaning & Manipulation
# Objective: Practice cleaning data and manipulating DataFrames.

# Question 1: Handling Missing Values
# 9. Use the fillna() method to fill missing values with a specific value.





import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, None, 30, None],
        'City': ['New York', 'Los Angeles', 'Chicago', None]}

df = pd.DataFrame(data)


df['Age'] = df['Age'].fillna(0)  
df['City'] = df['City'].fillna('Unknown')  

print(df)



df = df.rename(columns={'Name': 'Full Name', 'Age': 'Age (years)', 'City': 'City of Residence'})

print(df)


df = pd.concat([df, df], ignore_index=True)


df = df.drop_duplicates()

print(df)
# QUestion 2: Renaming Columns
# 10. Change the names of specific columns using rename().




# Question 3: Dropping Duplicates
# 11. Remove duplicate rows from the DataFrame.

      Name   Age         City
0    Alice  25.0     New York
1      Bob   0.0  Los Angeles
2  Charlie  30.0      Chicago
3    David   0.0      Unknown
  Full Name  Age (years) City of Residence
0     Alice         25.0          New York
1       Bob          0.0       Los Angeles
2   Charlie         30.0           Chicago
3     David          0.0           Unknown
  Full Name  Age (years) City of Residence
0     Alice         25.0          New York
1       Bob          0.0       Los Angeles
2   Charlie         30.0           Chicago
3     David          0.0           Unknown

In [36]:
# Data Aggregation & Exporting
# Objective: Aggregate data and export the results.

# Question 1: Grouping and Aggregating Data
# 12. Group data by a specific column and calculate the mean for each group.
import pandas as pd 
df = pd.DataFrame({
    'Category': ['A', 'B', 'A', 'B', 'A'],'Value':[10,20,30,40,50]
})
grouped_mean = df.groupby('Category').mean()
print(grouped_mean)
grouped_mean.to_csv('grouped_mean.csv',index = True)
grouped_multi = df.groupby('Category').agg({'Value':['mean','sum','max']})
print(grouped_multi)





# Question 2: Exporting Data to CSV
# 13. Export the DataFrame to a new CSV file.





# Question 3: Aggregating with Multiple Functions
# 14. Apply several aggregate functions to the grouped data.

          Value
Category
A          30.0
B          30.0
         Value
          mean sum max
Category
A         30.0  90  50
B         30.0  60  40