In [3]:
# Part 1: Handle Missing Values & Duplicates

    # Step-by-Step Guidelines:
# 1. Load the Data: First, ensure you have pandas installed and import it.
# 2. Handling Missing Values
#     1. Identify Missing Values:
#     2. Fill Missing Values:
# 3. Handling Duplicates
#     1. Identify Duplicates:
#     2. Remove Duplicates:
# 4. Combined Practice on a New Dataset
#     1. New Sample Data:
#     2. Handling Missing Values:
#     3. Remove Duplicates:
        
        
        
        
        # Step 1: Import the necessary library
import pandas as pd
import numpy as np

# Step 2: Load the Data
# For this example, we will create a sample dataset

data = {
    'ID': [1, 2, 3, 4, 5, 6, 7],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice', None],
    'Age': [25, 30, None, 35, 40, 25, 30],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'F', None],
    'Salary': [50000, None, 60000, 70000, None, 50000, 55000]
}

df = pd.DataFrame(data)

# Step 3: Handling Missing Values
# 3.1 Identify Missing Values
print("Missing Values in the DataFrame:")
print(df.isnull().sum())

# 3.2 Fill Missing Values
# Filling missing values in 'Age' with the mean of the column
df['Age'].fillna(df['Age'].mean(), inplace=True)

# Filling missing values in 'Gender' with the mode (most frequent value)
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

# Filling missing values in 'Salary' with the median of the column
df['Salary'].fillna(df['Salary'].median(), inplace=True)

print("\nData after handling missing values:")
print(df)

# Step 4: Handling Duplicates
# 4.1 Identify Duplicates
print("\nDuplicate Entries in the DataFrame:")
print(df.duplicated().sum())

# 4.2 Remove Duplicates
# Remove duplicate rows based on all columns
df.drop_duplicates(inplace=True)

print("\nData after removing duplicates:")
print(df)

# Step 5: Combined Practice on a New Dataset
# 5.1 New Sample Data
data_new = {
    'ID': [8, 9, 10, 11, 12, 13],
    'Name': ['Grace', 'Helen', 'Alice', 'Ivan', 'John', 'Alice'],
    'Age': [29, None, 30, 25, 33, None],
    'Gender': ['F', 'F', 'F', 'M', 'M', 'M'],
    'Salary': [65000, 70000, None, 55000, 75000, 60000]
}

df_new = pd.DataFrame(data_new)

# 5.2 Handling Missing Values
df_new['Age'].fillna(df_new['Age'].mean(), inplace=True)
df_new['Salary'].fillna(df_new['Salary'].median(), inplace=True)

# 5.3 Remove Duplicates
df_new.drop_duplicates(inplace=True)

print("\nNew Data after handling missing values and duplicates:")
print(df_new)

Missing Values in the DataFrame:
ID        0
Name      1
Age       1
Gender    1
Salary    2
dtype: int64

Data after handling missing values:
   ID     Name        Age Gender   Salary
0   1    Alice  25.000000      F  50000.0
1   2      Bob  30.000000      M  55000.0
2   3  Charlie  30.833333      M  60000.0
3   4    David  35.000000      M  70000.0
4   5      Eve  40.000000      F  55000.0
5   6    Alice  25.000000      F  50000.0
6   7     None  30.000000      F  55000.0

Duplicate Entries in the DataFrame:
0

Data after removing duplicates:
   ID     Name        Age Gender   Salary
0   1    Alice  25.000000      F  50000.0
1   2      Bob  30.000000      M  55000.0
2   3  Charlie  30.833333      M  60000.0
3   4    David  35.000000      M  70000.0
4   5      Eve  40.000000      F  55000.0
5   6    Alice  25.000000      F  50000.0
6   7     None  30.000000      F  55000.0

New Data after handling missing values and duplicates:
   ID   Name    Age Gender   Salary
0   8  Grace  29.00      F  65000.0
1   9  Helen  29.25      F  70000.0
2  10  Alice  30.00      F  65000.0
3  11   Ivan  25.00      M  55000.0
4  12   John  33.00      M  75000.0
5  13  Alice  29.25      M  60000.0

In [4]:
# Part 2: Apply Standardization & Formatting Rules

#     Step-by-Step Guidelines:
# 1. Standardize Text Data
#     1. Convert All Names to Lowercase:
# 2. Format Numerical Data
#     1. Round Age Column to the Nearest Integer:
# 3. Combined Practice on Another Dataset
#     1. New Sample Data:
#     2. Standardize Product Names:
#     3. Format Prices to Two Decimal Places:
        # Step 1: Import the necessary library
import pandas as pd
import numpy as np

# Step 2: Load the Data
# For this example, we will create a sample dataset

data = {
    'ID': [1, 2, 3, 4, 5, 6, 7],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Alice', None],
    'Age': [25, 30, None, 35, 40, 25, 30],
    'Gender': ['F', 'M', 'M', 'M', 'F', 'F', None],
    'Salary': [50000, None, 60000, 70000, None, 50000, 55000]
}

df = pd.DataFrame(data)

# Step 3: Handling Missing Values
# 3.1 Identify Missing Values
print("Missing Values in the DataFrame:")
print(df.isnull().sum())

# 3.2 Fill Missing Values
# Filling missing values in 'Age' with the mean of the column
df['Age'].fillna(df['Age'].mean(), inplace=True)

# Filling missing values in 'Gender' with the mode (most frequent value)
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)

# Filling missing values in 'Salary' with the median of the column
df['Salary'].fillna(df['Salary'].median(), inplace=True)

print("\nData after handling missing values:")
print(df)

# Step 4: Handling Duplicates
# 4.1 Identify Duplicates
print("\nDuplicate Entries in the DataFrame:")
print(df.duplicated().sum())

# 4.2 Remove Duplicates
# Remove duplicate rows based on all columns
df.drop_duplicates(inplace=True)

print("\nData after removing duplicates:")
print(df)

# Step 5: Combined Practice on a New Dataset
# 5.1 New Sample Data
data_new = {
    'ID': [8, 9, 10, 11, 12, 13],
    'Name': ['Grace', 'Helen', 'Alice', 'Ivan', 'John', 'Alice'],
    'Age': [29, None, 30, 25, 33, None],
    'Gender': ['F', 'F', 'F', 'M', 'M', 'M'],
    'Salary': [65000, 70000, None, 55000, 75000, 60000]
}

df_new = pd.DataFrame(data_new)

# 5.2 Handling Missing Values
df_new['Age'].fillna(df_new['Age'].mean(), inplace=True)
df_new['Salary'].fillna(df_new['Salary'].median(), inplace=True)

# 5.3 Remove Duplicates
df_new.drop_duplicates(inplace=True)

print("\nNew Data after handling missing values and duplicates:")
print(df_new)

Missing Values in the DataFrame:
ID        0
Name      1
Age       1
Gender    1
Salary    2
dtype: int64

Data after handling missing values:
   ID     Name        Age Gender   Salary
0   1    Alice  25.000000      F  50000.0
1   2      Bob  30.000000      M  55000.0
2   3  Charlie  30.833333      M  60000.0
3   4    David  35.000000      M  70000.0
4   5      Eve  40.000000      F  55000.0
5   6    Alice  25.000000      F  50000.0
6   7     None  30.000000      F  55000.0

Duplicate Entries in the DataFrame:
0

Data after removing duplicates:
   ID     Name        Age Gender   Salary
0   1    Alice  25.000000      F  50000.0
1   2      Bob  30.000000      M  55000.0
2   3  Charlie  30.833333      M  60000.0
3   4    David  35.000000      M  70000.0
4   5      Eve  40.000000      F  55000.0
5   6    Alice  25.000000      F  50000.0
6   7     None  30.000000      F  55000.0

New Data after handling missing values and duplicates:
   ID   Name    Age Gender   Salary
0   8  Grace  29.00      F  65000.0
1   9  Helen  29.25      F  70000.0
2  10  Alice  30.00      F  65000.0
3  11   Ivan  25.00      M  55000.0
4  12   John  33.00      M  75000.0
5  13  Alice  29.25      M  60000.0